# https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html
property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-file: /src/configs/model/face_detection/fd_lpd.caffemodel
  proto-file: /src/configs/model/face_detection/fd_lpd.prototxt
  model-engine-file: /src/configs/model/face_detection/fd_lpd.caffemodel_b1_gpu0_fp32.engine
  labelfile-path: /src/configs/model/face_detection/labels.txt

  batch-size: 1
  process-mode: 1
  model-color-format: 0
  ## 0=FP32, 1=INT8, 2=FP16
  network-mode: 0
  num-detected-classes: 4
  interval: 0
  filter-out-class-ids: 1;2;3
  gie-unique-id: 1
  output-blob-names: output_bbox;output_cov
  cluster-mode: 3


class-attrs-all:
  pre-cluster-threshold: 0.2
  topk: 20
  group-threshold: 1
  nms-iou-threshold: 0.5
  roi-top-offset: 0
  roi-bottom-offset: 0
  detected-min-w: 0
  detected-min-h: 0
  detected-max-w: 1920
  detected-max-h: 1920

# Per class configuration
# ONLY INTERESTED IN CLASS 0 (Face) AND CLASS 1 (License Plate)
# CHANGE THRESH OF CLASS 1 AND CLASS 2 TO > 1 TO REJECT THE DETECTION
class-attrs-0:
  threshold: 0.4
  pre-cluster-threshold: 0.4
  nms-iou-threshold: 0.7
  group-threshold: 1
  dbscan-min-score: 0.7
  eps: 0.3
  roi-top-offset: 0
  roi-bottom-offset: 0
  detected-min-w: 0
  detected-min-h: 0
  detected-max-w: 1920
  detected-max-h: 1920


