---

- name: [apt.yml] APT install [general]
  apt:
    name:
      - curl
      - zip
      - unzip
      - tar
      - git
      - software-properties-common
      - ccache
      - wget
      - graphviz
      - tmux
      - netcat
      - net-tools
      - nmap
      - vim
      - nano
      - ffmpeg
      - iputils-ping
    state: present

- name: [apt.yml] APT install [gstreamer]
  apt:
    name:
      - libgirepository1.0-dev
      - python3-gst-1.0
      - gir1.2-gst-rtsp-server-1.0
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-doc
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-qt5
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base-apps
      - libx264-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgstrtspserver-1.0-dev
    state: present

- name: [apt.yml] APT install [opencv]
  apt:
    name:
      - cmake
      - gcc
      - g++
      - ccache
      - python3
      - python3-dev
      - python3-numpy
      - python3-pip
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libpng-dev
      - libjpeg-dev
      - libopenexr-dev
      - libtiff-dev
      - libwebp-dev
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
    state: present

- name: [apt.yml] APT install [project]
  apt:
    name:
      - autoconf
      - automake
      - libtool
      - gcc
      - g++
      - build-essential
      - ninja-build
      - v4l-utils
      - pkg-config
      - uuid-dev
      - tzdata
      - libgflags-dev
      - libgoogle-glog-dev
      - libopencv-dev
      - libyaml-cpp-dev
      - nlohmann-json3-dev
    state: present

- name: [apt.yml] install glib
  command: apt-get install glib-2.0 -y