source:
  - element:
    name: v4l2src
    alias: source
  - element:
    name: queue
    alias: v4l2src_queue
  - element:
    name: videorate
    alias: src_rate
  - element:
    name: videoscale
    alias: src_scale
  - element:
    name: videoconvert
    alias: src_conv
  - element:
    name: capsfilter
    alias: src_caps
    property:
      - caps=video/x-raw,framerate=(fraction)15/1,width=(int)1920,height=(int)1080
  - element:
    name: nvvideoconvert
    alias: src_decoder
  - element:
    name: queue
    alias: src_queue
  - element:
    name: nvstreammux
    alias: nv_mux
    property:
      - nvbuf-memory-type=0
      - batch-size=1
      - width=1920
      - height=1080
      - batched-push-timeout=40000
      - sync-inputs=false
      - live-source=true
    link:
      type: request
      pad_name: sink_0
      link_element: src_queue
      link_pad: src
  - element:
    name: nvinfer
    alias: nv_detection
    property:
      - config-file-path=/src/configs/model/nvds/detection.yml
      - batch-size=1
      - qos=1
  - element:
    name: nvtracker
    alias: nv_tracker
    property:
      - ll-config-file=/src/configs/tracker.yml
      - ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
      - enable-batch-process=1
      - tracker-width=640
      - tracker-height=480
    callback:
      type: probe
      pad: src
      function_name: probe_callback
  - element:
    name: nvvideoconvert
    alias: nv_convert
    property:
      - compute-hw=1
  - element:
    name: videoconvert
    alias: sink_conv
  - element:
    name: capsfilter
    alias: sink_caps
    property:
      - caps=video/x-raw,format=(string)YV12
    callback:
      type: probe
      pad: src
      function_name: osd_callback
  - element:
    name: queue
    alias: sink_queue
  - element:
    name: xvimagesink
    alias: sink
    property:
      - sync=true


