source:
  - element:
    name: filesrc
    alias: source
    property:
      - location=/opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.mp4
  - element:
    name: qtdemux
    alias: src_demux
    callback:
      type: signal
      element_signal: pad-added
      function_name: on_pad_added
  - element:
    name: h264parse
    alias: src_parser
    link:
      type: ignore
  - element:
    name: nvv4l2decoder
    alias: src_decoder
#  - element:
#    name: capsfilter
#    alias: src_caps
#    property:
#      - caps=video/x-raw(memory:NVMM),format=(string)NV12
  - element:
    name: queue
    alias: src_queue
  - element:
    name: nvstreammux
    alias: nv_mux
    property:
      - nvbuf-memory-type=3
      - batch-size=1
      - width=1280
      - height=720
      - batched-push-timeout=40000
      - sync-inputs=false
      - live-source=false
    link:
      type: request
      pad_name: sink_0
      link_element: src_queue
      link_pad: src
  - element:
    name: nvinfer
    alias: nv_detection
    property:
      - config-file-path=/src/configs/model/nvds/detection.yml
      - qos=1
  - element:
    name: nvtracker
    alias: nv_tracker
    property:
#      - ll-config-file=/src/configs/tracker.yml
      - ll-config-file=/opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
      - ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
      - enable-batch-process=1
      - tracker-width=640
      - tracker-height=480
    callback:
      type: probe
      pad: src
      function_name: probe_callback
  - element:
    name: nvvideoconvert
    alias: nv_convert
    property:
      - compute-hw=1
  - element:
    name: videoconvert
    alias: sink_conv
  - element:
    name: capsfilter
    alias: sink_caps
    property:
#      - caps=video/x-raw,format=(string)NV12
      - caps=video/x-raw,format=(string)YV12
    callback:
      type: probe
      pad: src
      function_name: osd_callback
  - element:
    name: queue
    alias: sink_queue
  - element:
    name: x264enc
    alias: sink_encode
  - element:
    name: flvmux
    alias: sink_mux
    link:
      type: request
      pad_name: video
      link_element: sink_encode
      link_pad: src
  - element:
    name: queue
    alias: sink_queue2
  - element:
    name: filesink
    alias: sink
    property:
      - sync=false
      - async=true
      - location=nvds.mp4